package com.abstix.dao;

// Generated 23 nov. 2015 11:36:31 by Hibernate Tools 3.4.0.CR1

/**
 * Enseignements generated by hbm2java
 */
public class Enseignements implements java.io.Serializable {

	private Short id;
	private String code;
	private String intitule;
	private char niveau;
	private String semestre;
	private String optionE;
	private byte actif;
	private String version;
	private byte ok;
	private byte verrou;
	private String memo;
	private String objectifs;
	private String prerequisIndexes;
	private String prerequisTexte;
	private String pedagogie;
	private String pedagogieAlternance;
	private String evalRemarques;
	private String evalRemarquesAlternance;
	private String bibliographie;
	private String refDisciplines;
	private String refSavoirsfaire;
	private String refSavoirsetre;
	private String eadTexte;
	private String eadLien;
	private String eadNbh;
	private String eadNbh2;
	private String eadAlternanceNbh;
	private String eadAlternanceNbh2;
	private String fichierPresEns;
	private String datePresEns;
	private String nbhCours;
	private String nbhCours2;
	private String nbhTd;
	private String nbhTd2;
	private String nbhTp;
	private String nbhTp2;
	private String nbhProj;
	private String nbhProj2;
	private String nbhAutre;
	private String nbhAutre2;
	private byte tdi;
	private byte tpi;
	private String international;
	private String idDescripteur1;
	private String idDescripteur2;
	private String idDescripteur3;
	private short idRespEns;
	private int idRespCours;
	private int idRespTd;
	private int idRespTp;
	private int idRespProj;
	private int idRespAutre;
	private String fichierPresCours;
	private String fichierPresTd;
	private String fichierPresTp;
	private String fichierPresProj;
	private String fichierPresAutre;
	private byte coefCours;
	private byte coefTd;
	private byte coefTp;
	private byte coefProj;
	private byte coefAutre;
	private String dateModif;
	private String auteurModif;
	private String datePresCours;
	private String datePresTd;
	private String datePresTp;
	private String datePresProj;
	private String datePresAutre;

	public Enseignements() {
	}

	public Enseignements(String code, String intitule, char niveau,
			String semestre, String optionE, byte actif, String version,
			byte ok, byte verrou, String memo, String objectifs,
			String prerequisIndexes, String prerequisTexte, String pedagogie,
			String pedagogieAlternance, String evalRemarques,
			String evalRemarquesAlternance, String bibliographie,
			String refDisciplines, String refSavoirsfaire,
			String refSavoirsetre, String eadTexte, String eadLien,
			String eadNbh, String eadNbh2, String eadAlternanceNbh,
			String eadAlternanceNbh2, String fichierPresEns,
			String datePresEns, String nbhCours, String nbhCours2,
			String nbhTd, String nbhTd2, String nbhTp, String nbhTp2,
			String nbhProj, String nbhProj2, String nbhAutre, String nbhAutre2,
			byte tdi, byte tpi, String international, String idDescripteur1,
			String idDescripteur2, String idDescripteur3, short idRespEns,
			int idRespCours, int idRespTd, int idRespTp, int idRespProj,
			int idRespAutre, String fichierPresCours, String fichierPresTd,
			String fichierPresTp, String fichierPresProj,
			String fichierPresAutre, byte coefCours, byte coefTd, byte coefTp,
			byte coefProj, byte coefAutre, String dateModif,
			String auteurModif, String datePresCours, String datePresTd,
			String datePresTp, String datePresProj, String datePresAutre) {
		this.code = code;
		this.intitule = intitule;
		this.niveau = niveau;
		this.semestre = semestre;
		this.optionE = optionE;
		this.actif = actif;
		this.version = version;
		this.ok = ok;
		this.verrou = verrou;
		this.memo = memo;
		this.objectifs = objectifs;
		this.prerequisIndexes = prerequisIndexes;
		this.prerequisTexte = prerequisTexte;
		this.pedagogie = pedagogie;
		this.pedagogieAlternance = pedagogieAlternance;
		this.evalRemarques = evalRemarques;
		this.evalRemarquesAlternance = evalRemarquesAlternance;
		this.bibliographie = bibliographie;
		this.refDisciplines = refDisciplines;
		this.refSavoirsfaire = refSavoirsfaire;
		this.refSavoirsetre = refSavoirsetre;
		this.eadTexte = eadTexte;
		this.eadLien = eadLien;
		this.eadNbh = eadNbh;
		this.eadNbh2 = eadNbh2;
		this.eadAlternanceNbh = eadAlternanceNbh;
		this.eadAlternanceNbh2 = eadAlternanceNbh2;
		this.fichierPresEns = fichierPresEns;
		this.datePresEns = datePresEns;
		this.nbhCours = nbhCours;
		this.nbhCours2 = nbhCours2;
		this.nbhTd = nbhTd;
		this.nbhTd2 = nbhTd2;
		this.nbhTp = nbhTp;
		this.nbhTp2 = nbhTp2;
		this.nbhProj = nbhProj;
		this.nbhProj2 = nbhProj2;
		this.nbhAutre = nbhAutre;
		this.nbhAutre2 = nbhAutre2;
		this.tdi = tdi;
		this.tpi = tpi;
		this.international = international;
		this.idDescripteur1 = idDescripteur1;
		this.idDescripteur2 = idDescripteur2;
		this.idDescripteur3 = idDescripteur3;
		this.idRespEns = idRespEns;
		this.idRespCours = idRespCours;
		this.idRespTd = idRespTd;
		this.idRespTp = idRespTp;
		this.idRespProj = idRespProj;
		this.idRespAutre = idRespAutre;
		this.fichierPresCours = fichierPresCours;
		this.fichierPresTd = fichierPresTd;
		this.fichierPresTp = fichierPresTp;
		this.fichierPresProj = fichierPresProj;
		this.fichierPresAutre = fichierPresAutre;
		this.coefCours = coefCours;
		this.coefTd = coefTd;
		this.coefTp = coefTp;
		this.coefProj = coefProj;
		this.coefAutre = coefAutre;
		this.dateModif = dateModif;
		this.auteurModif = auteurModif;
		this.datePresCours = datePresCours;
		this.datePresTd = datePresTd;
		this.datePresTp = datePresTp;
		this.datePresProj = datePresProj;
		this.datePresAutre = datePresAutre;
	}

	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getIntitule() {
		return this.intitule;
	}

	public void setIntitule(String intitule) {
		this.intitule = intitule;
	}

	public char getNiveau() {
		return this.niveau;
	}

	public void setNiveau(char niveau) {
		this.niveau = niveau;
	}

	public String getSemestre() {
		return this.semestre;
	}

	public void setSemestre(String semestre) {
		this.semestre = semestre;
	}

	public String getOptionE() {
		return this.optionE;
	}

	public void setOptionE(String optionE) {
		this.optionE = optionE;
	}

	public byte getActif() {
		return this.actif;
	}

	public void setActif(byte actif) {
		this.actif = actif;
	}

	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public byte getOk() {
		return this.ok;
	}

	public void setOk(byte ok) {
		this.ok = ok;
	}

	public byte getVerrou() {
		return this.verrou;
	}

	public void setVerrou(byte verrou) {
		this.verrou = verrou;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getObjectifs() {
		return this.objectifs;
	}

	public void setObjectifs(String objectifs) {
		this.objectifs = objectifs;
	}

	public String getPrerequisIndexes() {
		return this.prerequisIndexes;
	}

	public void setPrerequisIndexes(String prerequisIndexes) {
		this.prerequisIndexes = prerequisIndexes;
	}

	public String getPrerequisTexte() {
		return this.prerequisTexte;
	}

	public void setPrerequisTexte(String prerequisTexte) {
		this.prerequisTexte = prerequisTexte;
	}

	public String getPedagogie() {
		return this.pedagogie;
	}

	public void setPedagogie(String pedagogie) {
		this.pedagogie = pedagogie;
	}

	public String getPedagogieAlternance() {
		return this.pedagogieAlternance;
	}

	public void setPedagogieAlternance(String pedagogieAlternance) {
		this.pedagogieAlternance = pedagogieAlternance;
	}

	public String getEvalRemarques() {
		return this.evalRemarques;
	}

	public void setEvalRemarques(String evalRemarques) {
		this.evalRemarques = evalRemarques;
	}

	public String getEvalRemarquesAlternance() {
		return this.evalRemarquesAlternance;
	}

	public void setEvalRemarquesAlternance(String evalRemarquesAlternance) {
		this.evalRemarquesAlternance = evalRemarquesAlternance;
	}

	public String getBibliographie() {
		return this.bibliographie;
	}

	public void setBibliographie(String bibliographie) {
		this.bibliographie = bibliographie;
	}

	public String getRefDisciplines() {
		return this.refDisciplines;
	}

	public void setRefDisciplines(String refDisciplines) {
		this.refDisciplines = refDisciplines;
	}

	public String getRefSavoirsfaire() {
		return this.refSavoirsfaire;
	}

	public void setRefSavoirsfaire(String refSavoirsfaire) {
		this.refSavoirsfaire = refSavoirsfaire;
	}

	public String getRefSavoirsetre() {
		return this.refSavoirsetre;
	}

	public void setRefSavoirsetre(String refSavoirsetre) {
		this.refSavoirsetre = refSavoirsetre;
	}

	public String getEadTexte() {
		return this.eadTexte;
	}

	public void setEadTexte(String eadTexte) {
		this.eadTexte = eadTexte;
	}

	public String getEadLien() {
		return this.eadLien;
	}

	public void setEadLien(String eadLien) {
		this.eadLien = eadLien;
	}

	public String getEadNbh() {
		return this.eadNbh;
	}

	public void setEadNbh(String eadNbh) {
		this.eadNbh = eadNbh;
	}

	public String getEadNbh2() {
		return this.eadNbh2;
	}

	public void setEadNbh2(String eadNbh2) {
		this.eadNbh2 = eadNbh2;
	}

	public String getEadAlternanceNbh() {
		return this.eadAlternanceNbh;
	}

	public void setEadAlternanceNbh(String eadAlternanceNbh) {
		this.eadAlternanceNbh = eadAlternanceNbh;
	}

	public String getEadAlternanceNbh2() {
		return this.eadAlternanceNbh2;
	}

	public void setEadAlternanceNbh2(String eadAlternanceNbh2) {
		this.eadAlternanceNbh2 = eadAlternanceNbh2;
	}

	public String getFichierPresEns() {
		return this.fichierPresEns;
	}

	public void setFichierPresEns(String fichierPresEns) {
		this.fichierPresEns = fichierPresEns;
	}

	public String getDatePresEns() {
		return this.datePresEns;
	}

	public void setDatePresEns(String datePresEns) {
		this.datePresEns = datePresEns;
	}

	public String getNbhCours() {
		return this.nbhCours;
	}

	public void setNbhCours(String nbhCours) {
		this.nbhCours = nbhCours;
	}

	public String getNbhCours2() {
		return this.nbhCours2;
	}

	public void setNbhCours2(String nbhCours2) {
		this.nbhCours2 = nbhCours2;
	}

	public String getNbhTd() {
		return this.nbhTd;
	}

	public void setNbhTd(String nbhTd) {
		this.nbhTd = nbhTd;
	}

	public String getNbhTd2() {
		return this.nbhTd2;
	}

	public void setNbhTd2(String nbhTd2) {
		this.nbhTd2 = nbhTd2;
	}

	public String getNbhTp() {
		return this.nbhTp;
	}

	public void setNbhTp(String nbhTp) {
		this.nbhTp = nbhTp;
	}

	public String getNbhTp2() {
		return this.nbhTp2;
	}

	public void setNbhTp2(String nbhTp2) {
		this.nbhTp2 = nbhTp2;
	}

	public String getNbhProj() {
		return this.nbhProj;
	}

	public void setNbhProj(String nbhProj) {
		this.nbhProj = nbhProj;
	}

	public String getNbhProj2() {
		return this.nbhProj2;
	}

	public void setNbhProj2(String nbhProj2) {
		this.nbhProj2 = nbhProj2;
	}

	public String getNbhAutre() {
		return this.nbhAutre;
	}

	public void setNbhAutre(String nbhAutre) {
		this.nbhAutre = nbhAutre;
	}

	public String getNbhAutre2() {
		return this.nbhAutre2;
	}

	public void setNbhAutre2(String nbhAutre2) {
		this.nbhAutre2 = nbhAutre2;
	}

	public byte getTdi() {
		return this.tdi;
	}

	public void setTdi(byte tdi) {
		this.tdi = tdi;
	}

	public byte getTpi() {
		return this.tpi;
	}

	public void setTpi(byte tpi) {
		this.tpi = tpi;
	}

	public String getInternational() {
		return this.international;
	}

	public void setInternational(String international) {
		this.international = international;
	}

	public String getIdDescripteur1() {
		return this.idDescripteur1;
	}

	public void setIdDescripteur1(String idDescripteur1) {
		this.idDescripteur1 = idDescripteur1;
	}

	public String getIdDescripteur2() {
		return this.idDescripteur2;
	}

	public void setIdDescripteur2(String idDescripteur2) {
		this.idDescripteur2 = idDescripteur2;
	}

	public String getIdDescripteur3() {
		return this.idDescripteur3;
	}

	public void setIdDescripteur3(String idDescripteur3) {
		this.idDescripteur3 = idDescripteur3;
	}

	public short getIdRespEns() {
		return this.idRespEns;
	}

	public void setIdRespEns(short idRespEns) {
		this.idRespEns = idRespEns;
	}

	public int getIdRespCours() {
		return this.idRespCours;
	}

	public void setIdRespCours(int idRespCours) {
		this.idRespCours = idRespCours;
	}

	public int getIdRespTd() {
		return this.idRespTd;
	}

	public void setIdRespTd(int idRespTd) {
		this.idRespTd = idRespTd;
	}

	public int getIdRespTp() {
		return this.idRespTp;
	}

	public void setIdRespTp(int idRespTp) {
		this.idRespTp = idRespTp;
	}

	public int getIdRespProj() {
		return this.idRespProj;
	}

	public void setIdRespProj(int idRespProj) {
		this.idRespProj = idRespProj;
	}

	public int getIdRespAutre() {
		return this.idRespAutre;
	}

	public void setIdRespAutre(int idRespAutre) {
		this.idRespAutre = idRespAutre;
	}

	public String getFichierPresCours() {
		return this.fichierPresCours;
	}

	public void setFichierPresCours(String fichierPresCours) {
		this.fichierPresCours = fichierPresCours;
	}

	public String getFichierPresTd() {
		return this.fichierPresTd;
	}

	public void setFichierPresTd(String fichierPresTd) {
		this.fichierPresTd = fichierPresTd;
	}

	public String getFichierPresTp() {
		return this.fichierPresTp;
	}

	public void setFichierPresTp(String fichierPresTp) {
		this.fichierPresTp = fichierPresTp;
	}

	public String getFichierPresProj() {
		return this.fichierPresProj;
	}

	public void setFichierPresProj(String fichierPresProj) {
		this.fichierPresProj = fichierPresProj;
	}

	public String getFichierPresAutre() {
		return this.fichierPresAutre;
	}

	public void setFichierPresAutre(String fichierPresAutre) {
		this.fichierPresAutre = fichierPresAutre;
	}

	public byte getCoefCours() {
		return this.coefCours;
	}

	public void setCoefCours(byte coefCours) {
		this.coefCours = coefCours;
	}

	public byte getCoefTd() {
		return this.coefTd;
	}

	public void setCoefTd(byte coefTd) {
		this.coefTd = coefTd;
	}

	public byte getCoefTp() {
		return this.coefTp;
	}

	public void setCoefTp(byte coefTp) {
		this.coefTp = coefTp;
	}

	public byte getCoefProj() {
		return this.coefProj;
	}

	public void setCoefProj(byte coefProj) {
		this.coefProj = coefProj;
	}

	public byte getCoefAutre() {
		return this.coefAutre;
	}

	public void setCoefAutre(byte coefAutre) {
		this.coefAutre = coefAutre;
	}

	public String getDateModif() {
		return this.dateModif;
	}

	public void setDateModif(String dateModif) {
		this.dateModif = dateModif;
	}

	public String getAuteurModif() {
		return this.auteurModif;
	}

	public void setAuteurModif(String auteurModif) {
		this.auteurModif = auteurModif;
	}

	public String getDatePresCours() {
		return this.datePresCours;
	}

	public void setDatePresCours(String datePresCours) {
		this.datePresCours = datePresCours;
	}

	public String getDatePresTd() {
		return this.datePresTd;
	}

	public void setDatePresTd(String datePresTd) {
		this.datePresTd = datePresTd;
	}

	public String getDatePresTp() {
		return this.datePresTp;
	}

	public void setDatePresTp(String datePresTp) {
		this.datePresTp = datePresTp;
	}

	public String getDatePresProj() {
		return this.datePresProj;
	}

	public void setDatePresProj(String datePresProj) {
		this.datePresProj = datePresProj;
	}

	public String getDatePresAutre() {
		return this.datePresAutre;
	}

	public void setDatePresAutre(String datePresAutre) {
		this.datePresAutre = datePresAutre;
	}

}
