package com.abstix.dao;

// Generated 23 nov. 2015 11:36:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EtudiantsAbsences generated by hbm2java
 */
public class EtudiantsAbsences implements java.io.Serializable {

	private Short id;
	private int idEtu;
	private short idEns;
	private short idDisci;
	private String type;
	private Date date;
	private String ampm;
	private String motif;
	private char justif;
	private byte exam;

	public EtudiantsAbsences() {
	}

	public EtudiantsAbsences(int idEtu, short idEns, short idDisci,
			String type, String ampm, String motif, char justif, byte exam) {
		this.idEtu = idEtu;
		this.idEns = idEns;
		this.idDisci = idDisci;
		this.type = type;
		this.ampm = ampm;
		this.motif = motif;
		this.justif = justif;
		this.exam = exam;
	}

	public EtudiantsAbsences(int idEtu, short idEns, short idDisci,
			String type, Date date, String ampm, String motif, char justif,
			byte exam) {
		this.idEtu = idEtu;
		this.idEns = idEns;
		this.idDisci = idDisci;
		this.type = type;
		this.date = date;
		this.ampm = ampm;
		this.motif = motif;
		this.justif = justif;
		this.exam = exam;
	}

	public Short getId() {
		return this.id;
	}

	public void setId(Short id) {
		this.id = id;
	}

	public int getIdEtu() {
		return this.idEtu;
	}

	public void setIdEtu(int idEtu) {
		this.idEtu = idEtu;
	}

	public short getIdEns() {
		return this.idEns;
	}

	public void setIdEns(short idEns) {
		this.idEns = idEns;
	}

	public short getIdDisci() {
		return this.idDisci;
	}

	public void setIdDisci(short idDisci) {
		this.idDisci = idDisci;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getAmpm() {
		return this.ampm;
	}

	public void setAmpm(String ampm) {
		this.ampm = ampm;
	}

	public String getMotif() {
		return this.motif;
	}

	public void setMotif(String motif) {
		this.motif = motif;
	}

	public char getJustif() {
		return this.justif;
	}

	public void setJustif(char justif) {
		this.justif = justif;
	}

	public byte getExam() {
		return this.exam;
	}

	public void setExam(byte exam) {
		this.exam = exam;
	}

}
