package com.abstix.dao;

// Generated 23 nov. 2015 11:36:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Inscriptions2 generated by hbm2java
 */
public class Inscriptions2 implements java.io.Serializable {

	private Integer id;
	private String login;
	private String login2;
	private String mdpHash;
	private String uuidUdm;
	private String civilite;
	private String nom;
	private String prenom;
	private String nomjfille;
	private String prononciation;
	private Date datenaiss;
	private String villenaiss;
	private String dptnaiss;
	private String paysnaiss;
	private String nationalite;
	private String sitfam;
	private String nom1;
	private String rue1;
	private String cp1;
	private String ville1;
	private String tel1;
	private String fax;
	private String pays1;
	private String nom2;
	private String rue2;
	private String cp2;
	private String ville2;
	private String tel2;
	private String pays2;
	private String connaissance;
	private byte alternance;
	private String origine;
	private String echangeProgram;
	private String echangeProfNom;
	private String echangeProfFonction;
	private String echangeProfEmail;
	private String candiploNiveau;
	private String candiploType;
	private String candiploIntitule;
	private String filiere;
	private String concours;
	private String emploi;
	private String nometa;
	private String rueeta;
	private String cpeta;
	private String villeeta;
	private String payseta;
	private String teleta;
	private String seriebac;
	private String mentionbac;
	private String anneebac;
	private String lyceebac;
	private String villebac;
	private String paysbac;
	private String bea;
	private String anneesuivibac1;
	private String anneesuivibac2;
	private String anneesuivibac3;
	private String etasuivibac1;
	private String etasuivibac2;
	private String etasuivibac3;
	private String filsuivibac1;
	private String filsuivibac2;
	private String filsuivibac3;
	private String resultatsuivibac1;
	private String resultatsuivibac2;
	private String resultatsuivibac3;
	private String moygesuivibac1;
	private String moygesuivibac2;
	private String moygesuivibac3;
	private String moyangsuivibac1;
	private String moyangsuivibac2;
	private String moyangsuivibac3;
	private String suivibacBreak;
	private byte[] stages;
	private byte[] sejours;
	private String langue1;
	private String langue2;
	private String langue3;
	private String carteid;
	private String attesdiplome;
	private String photo;
	private String cv;
	private String cvOk;
	private String lettreMotiv;
	private String motiv;
	private String cheque;
	private String bacPhotocopie;
	private String notes3annees;
	private String avis1;
	private String avis2;
	private String dossierCampusFrance;
	private String campusFrance;
	private Date dateConstitutionDossier;
	private Date dateDemandeConfirmationDossier;
	private byte valide;
	private Date dateConfirmationDossier;
	private byte abandon;
	private String abandonMotif;
	private Date dateReceptionImprime;
	private String dossierRapporteur1;
	private String dossierRapporteur2;
	private int dossierNote1;
	private int dossierNote2;
	private String statutDossier;
	private Date dateStatutDossier;
	private byte notifStatutDossier;
	private String entretienAuditeur1;
	private String entretienAuditeur2;
	private String entretienSalle;
	private String entretienHeure;
	private int entretienNote;
	private Date dateChoixSouhaits;
	private Date dateChoix1;
	private Date dateChoix2;
	private Date dateSession;
	private String entretienChoixRetenu;
	private Date dateConvocation;
	private Date dateNotificationConvocation;
	private String statutEntretien;
	private Date dateStatutEntretien;
	private byte notifStatutEntretien;
	private String statutAdmission;
	private Date dateNotifAdmission;
	private short rang;
	private String statutInscription;
	private Date dateStatutInscription;
	private byte notifStatutInscription;
	private Date dateReceptionInscription;
	private Date dateDerniereConsultation;
	private String derniereVisiteAnticollision;
	private Date dateModifAdmin;
	private String nomModifAdmin;
	private byte statutDelete;
	private byte unlocked;
	private String etudiant;
	private String boursier;
	private String numUdm;
	private String mailUdm;
	private String mailPro;
	private String mailProNew;
	private String mailPerso;
	private String mailPersoNew;
	private String mailAutreNew;
	private byte noMaskedMail;
	private String promoEntree;
	private String promo;
	private String optionSpCandi;
	private String optionSp;
	private String td;
	private String tp;
	private String gt1;
	private String gt2;
	private String gt3;
	private String gt4;
	private String gt5;
	private String gt6;
	private String handicap;
	private String activiteRemuneree;
	private String absencePerm;
	private String absencesLongues;
	private byte ajac;
	private String redoublant;
	private String cursus;
	private short idEnsApprenti;
	private String matieresIntraorg;
	private char stageFacultatif;
	private String relinterDisp;
	private String toic;
	private String commentaire;
	private String reponse;
	private String anneeCivileEntree;
	private String anneeCivileSortie;
	private String anneeCivileDiplome;
	private char motifSortie;
	private String photoAlu;
	private int employeurId;
	private String employeurSiret;
	private String employeurApe;
	private String employeurUrl;
	private String emploiFonction;
	private byte emploiSecteurId;
	private byte emploiType1;
	private byte emploiType2;
	private String emploiMotcleL;
	private String web1;
	private String web2;
	private String annuaireInfos;
	private String annuaireDiffusion;
	private String actionsEnsim;

	public Inscriptions2() {
	}

	public Inscriptions2(String login, String login2, String mdpHash,
			String uuidUdm, String civilite, String nom, String prenom,
			String nomjfille, String prononciation, String villenaiss,
			String dptnaiss, String paysnaiss, String nationalite,
			String sitfam, String nom1, String rue1, String cp1, String ville1,
			String tel1, String fax, String pays1, String nom2, String rue2,
			String cp2, String ville2, String tel2, String pays2,
			String connaissance, byte alternance, String origine,
			String echangeProgram, String echangeProfNom,
			String echangeProfFonction, String echangeProfEmail,
			String candiploNiveau, String candiploType,
			String candiploIntitule, String filiere, String concours,
			String emploi, String nometa, String rueeta, String cpeta,
			String villeeta, String payseta, String teleta, String seriebac,
			String mentionbac, String anneebac, String lyceebac,
			String villebac, String paysbac, String bea, String anneesuivibac1,
			String anneesuivibac2, String anneesuivibac3, String etasuivibac1,
			String etasuivibac2, String etasuivibac3, String filsuivibac1,
			String filsuivibac2, String filsuivibac3, String resultatsuivibac1,
			String resultatsuivibac2, String resultatsuivibac3,
			String moygesuivibac1, String moygesuivibac2,
			String moygesuivibac3, String moyangsuivibac1,
			String moyangsuivibac2, String moyangsuivibac3,
			String suivibacBreak, String langue1, String langue2,
			String langue3, String carteid, String attesdiplome, String photo,
			String cv, String cvOk, String lettreMotiv, String motiv,
			String cheque, String bacPhotocopie, String notes3annees,
			String avis1, String avis2, String dossierCampusFrance,
			String campusFrance, byte valide, byte abandon,
			String abandonMotif, Date dateReceptionImprime,
			String dossierRapporteur1, String dossierRapporteur2,
			int dossierNote1, int dossierNote2, String statutDossier,
			byte notifStatutDossier, String entretienAuditeur1,
			String entretienAuditeur2, String entretienSalle,
			String entretienHeure, int entretienNote,
			String entretienChoixRetenu, String statutEntretien,
			byte notifStatutEntretien, String statutAdmission, short rang,
			String statutInscription, byte notifStatutInscription,
			String derniereVisiteAnticollision, Date dateModifAdmin,
			String nomModifAdmin, byte statutDelete, byte unlocked,
			String etudiant, String boursier, String numUdm, String mailUdm,
			String mailPro, String mailProNew, String mailPerso,
			String mailPersoNew, String mailAutreNew, byte noMaskedMail,
			String promoEntree, String promo, String optionSpCandi,
			String optionSp, String td, String tp, String gt1, String gt2,
			String gt3, String gt4, String gt5, String gt6, String handicap,
			String activiteRemuneree, String absencePerm,
			String absencesLongues, byte ajac, String redoublant,
			String cursus, short idEnsApprenti, String matieresIntraorg,
			char stageFacultatif, String relinterDisp, String toic,
			String commentaire, String reponse, String anneeCivileEntree,
			String anneeCivileSortie, String anneeCivileDiplome,
			char motifSortie, String photoAlu, int employeurId,
			String employeurSiret, String employeurApe, String employeurUrl,
			String emploiFonction, byte emploiSecteurId, byte emploiType1,
			byte emploiType2, String emploiMotcleL, String web1, String web2,
			String annuaireInfos, String annuaireDiffusion, String actionsEnsim) {
		this.login = login;
		this.login2 = login2;
		this.mdpHash = mdpHash;
		this.uuidUdm = uuidUdm;
		this.civilite = civilite;
		this.nom = nom;
		this.prenom = prenom;
		this.nomjfille = nomjfille;
		this.prononciation = prononciation;
		this.villenaiss = villenaiss;
		this.dptnaiss = dptnaiss;
		this.paysnaiss = paysnaiss;
		this.nationalite = nationalite;
		this.sitfam = sitfam;
		this.nom1 = nom1;
		this.rue1 = rue1;
		this.cp1 = cp1;
		this.ville1 = ville1;
		this.tel1 = tel1;
		this.fax = fax;
		this.pays1 = pays1;
		this.nom2 = nom2;
		this.rue2 = rue2;
		this.cp2 = cp2;
		this.ville2 = ville2;
		this.tel2 = tel2;
		this.pays2 = pays2;
		this.connaissance = connaissance;
		this.alternance = alternance;
		this.origine = origine;
		this.echangeProgram = echangeProgram;
		this.echangeProfNom = echangeProfNom;
		this.echangeProfFonction = echangeProfFonction;
		this.echangeProfEmail = echangeProfEmail;
		this.candiploNiveau = candiploNiveau;
		this.candiploType = candiploType;
		this.candiploIntitule = candiploIntitule;
		this.filiere = filiere;
		this.concours = concours;
		this.emploi = emploi;
		this.nometa = nometa;
		this.rueeta = rueeta;
		this.cpeta = cpeta;
		this.villeeta = villeeta;
		this.payseta = payseta;
		this.teleta = teleta;
		this.seriebac = seriebac;
		this.mentionbac = mentionbac;
		this.anneebac = anneebac;
		this.lyceebac = lyceebac;
		this.villebac = villebac;
		this.paysbac = paysbac;
		this.bea = bea;
		this.anneesuivibac1 = anneesuivibac1;
		this.anneesuivibac2 = anneesuivibac2;
		this.anneesuivibac3 = anneesuivibac3;
		this.etasuivibac1 = etasuivibac1;
		this.etasuivibac2 = etasuivibac2;
		this.etasuivibac3 = etasuivibac3;
		this.filsuivibac1 = filsuivibac1;
		this.filsuivibac2 = filsuivibac2;
		this.filsuivibac3 = filsuivibac3;
		this.resultatsuivibac1 = resultatsuivibac1;
		this.resultatsuivibac2 = resultatsuivibac2;
		this.resultatsuivibac3 = resultatsuivibac3;
		this.moygesuivibac1 = moygesuivibac1;
		this.moygesuivibac2 = moygesuivibac2;
		this.moygesuivibac3 = moygesuivibac3;
		this.moyangsuivibac1 = moyangsuivibac1;
		this.moyangsuivibac2 = moyangsuivibac2;
		this.moyangsuivibac3 = moyangsuivibac3;
		this.suivibacBreak = suivibacBreak;
		this.langue1 = langue1;
		this.langue2 = langue2;
		this.langue3 = langue3;
		this.carteid = carteid;
		this.attesdiplome = attesdiplome;
		this.photo = photo;
		this.cv = cv;
		this.cvOk = cvOk;
		this.lettreMotiv = lettreMotiv;
		this.motiv = motiv;
		this.cheque = cheque;
		this.bacPhotocopie = bacPhotocopie;
		this.notes3annees = notes3annees;
		this.avis1 = avis1;
		this.avis2 = avis2;
		this.dossierCampusFrance = dossierCampusFrance;
		this.campusFrance = campusFrance;
		this.valide = valide;
		this.abandon = abandon;
		this.abandonMotif = abandonMotif;
		this.dateReceptionImprime = dateReceptionImprime;
		this.dossierRapporteur1 = dossierRapporteur1;
		this.dossierRapporteur2 = dossierRapporteur2;
		this.dossierNote1 = dossierNote1;
		this.dossierNote2 = dossierNote2;
		this.statutDossier = statutDossier;
		this.notifStatutDossier = notifStatutDossier;
		this.entretienAuditeur1 = entretienAuditeur1;
		this.entretienAuditeur2 = entretienAuditeur2;
		this.entretienSalle = entretienSalle;
		this.entretienHeure = entretienHeure;
		this.entretienNote = entretienNote;
		this.entretienChoixRetenu = entretienChoixRetenu;
		this.statutEntretien = statutEntretien;
		this.notifStatutEntretien = notifStatutEntretien;
		this.statutAdmission = statutAdmission;
		this.rang = rang;
		this.statutInscription = statutInscription;
		this.notifStatutInscription = notifStatutInscription;
		this.derniereVisiteAnticollision = derniereVisiteAnticollision;
		this.dateModifAdmin = dateModifAdmin;
		this.nomModifAdmin = nomModifAdmin;
		this.statutDelete = statutDelete;
		this.unlocked = unlocked;
		this.etudiant = etudiant;
		this.boursier = boursier;
		this.numUdm = numUdm;
		this.mailUdm = mailUdm;
		this.mailPro = mailPro;
		this.mailProNew = mailProNew;
		this.mailPerso = mailPerso;
		this.mailPersoNew = mailPersoNew;
		this.mailAutreNew = mailAutreNew;
		this.noMaskedMail = noMaskedMail;
		this.promoEntree = promoEntree;
		this.promo = promo;
		this.optionSpCandi = optionSpCandi;
		this.optionSp = optionSp;
		this.td = td;
		this.tp = tp;
		this.gt1 = gt1;
		this.gt2 = gt2;
		this.gt3 = gt3;
		this.gt4 = gt4;
		this.gt5 = gt5;
		this.gt6 = gt6;
		this.handicap = handicap;
		this.activiteRemuneree = activiteRemuneree;
		this.absencePerm = absencePerm;
		this.absencesLongues = absencesLongues;
		this.ajac = ajac;
		this.redoublant = redoublant;
		this.cursus = cursus;
		this.idEnsApprenti = idEnsApprenti;
		this.matieresIntraorg = matieresIntraorg;
		this.stageFacultatif = stageFacultatif;
		this.relinterDisp = relinterDisp;
		this.toic = toic;
		this.commentaire = commentaire;
		this.reponse = reponse;
		this.anneeCivileEntree = anneeCivileEntree;
		this.anneeCivileSortie = anneeCivileSortie;
		this.anneeCivileDiplome = anneeCivileDiplome;
		this.motifSortie = motifSortie;
		this.photoAlu = photoAlu;
		this.employeurId = employeurId;
		this.employeurSiret = employeurSiret;
		this.employeurApe = employeurApe;
		this.employeurUrl = employeurUrl;
		this.emploiFonction = emploiFonction;
		this.emploiSecteurId = emploiSecteurId;
		this.emploiType1 = emploiType1;
		this.emploiType2 = emploiType2;
		this.emploiMotcleL = emploiMotcleL;
		this.web1 = web1;
		this.web2 = web2;
		this.annuaireInfos = annuaireInfos;
		this.annuaireDiffusion = annuaireDiffusion;
		this.actionsEnsim = actionsEnsim;
	}

	public Inscriptions2(String login, String login2, String mdpHash,
			String uuidUdm, String civilite, String nom, String prenom,
			String nomjfille, String prononciation, Date datenaiss,
			String villenaiss, String dptnaiss, String paysnaiss,
			String nationalite, String sitfam, String nom1, String rue1,
			String cp1, String ville1, String tel1, String fax, String pays1,
			String nom2, String rue2, String cp2, String ville2, String tel2,
			String pays2, String connaissance, byte alternance, String origine,
			String echangeProgram, String echangeProfNom,
			String echangeProfFonction, String echangeProfEmail,
			String candiploNiveau, String candiploType,
			String candiploIntitule, String filiere, String concours,
			String emploi, String nometa, String rueeta, String cpeta,
			String villeeta, String payseta, String teleta, String seriebac,
			String mentionbac, String anneebac, String lyceebac,
			String villebac, String paysbac, String bea, String anneesuivibac1,
			String anneesuivibac2, String anneesuivibac3, String etasuivibac1,
			String etasuivibac2, String etasuivibac3, String filsuivibac1,
			String filsuivibac2, String filsuivibac3, String resultatsuivibac1,
			String resultatsuivibac2, String resultatsuivibac3,
			String moygesuivibac1, String moygesuivibac2,
			String moygesuivibac3, String moyangsuivibac1,
			String moyangsuivibac2, String moyangsuivibac3,
			String suivibacBreak, byte[] stages, byte[] sejours,
			String langue1, String langue2, String langue3, String carteid,
			String attesdiplome, String photo, String cv, String cvOk,
			String lettreMotiv, String motiv, String cheque,
			String bacPhotocopie, String notes3annees, String avis1,
			String avis2, String dossierCampusFrance, String campusFrance,
			Date dateConstitutionDossier, Date dateDemandeConfirmationDossier,
			byte valide, Date dateConfirmationDossier, byte abandon,
			String abandonMotif, Date dateReceptionImprime,
			String dossierRapporteur1, String dossierRapporteur2,
			int dossierNote1, int dossierNote2, String statutDossier,
			Date dateStatutDossier, byte notifStatutDossier,
			String entretienAuditeur1, String entretienAuditeur2,
			String entretienSalle, String entretienHeure, int entretienNote,
			Date dateChoixSouhaits, Date dateChoix1, Date dateChoix2,
			Date dateSession, String entretienChoixRetenu,
			Date dateConvocation, Date dateNotificationConvocation,
			String statutEntretien, Date dateStatutEntretien,
			byte notifStatutEntretien, String statutAdmission,
			Date dateNotifAdmission, short rang, String statutInscription,
			Date dateStatutInscription, byte notifStatutInscription,
			Date dateReceptionInscription, Date dateDerniereConsultation,
			String derniereVisiteAnticollision, Date dateModifAdmin,
			String nomModifAdmin, byte statutDelete, byte unlocked,
			String etudiant, String boursier, String numUdm, String mailUdm,
			String mailPro, String mailProNew, String mailPerso,
			String mailPersoNew, String mailAutreNew, byte noMaskedMail,
			String promoEntree, String promo, String optionSpCandi,
			String optionSp, String td, String tp, String gt1, String gt2,
			String gt3, String gt4, String gt5, String gt6, String handicap,
			String activiteRemuneree, String absencePerm,
			String absencesLongues, byte ajac, String redoublant,
			String cursus, short idEnsApprenti, String matieresIntraorg,
			char stageFacultatif, String relinterDisp, String toic,
			String commentaire, String reponse, String anneeCivileEntree,
			String anneeCivileSortie, String anneeCivileDiplome,
			char motifSortie, String photoAlu, int employeurId,
			String employeurSiret, String employeurApe, String employeurUrl,
			String emploiFonction, byte emploiSecteurId, byte emploiType1,
			byte emploiType2, String emploiMotcleL, String web1, String web2,
			String annuaireInfos, String annuaireDiffusion, String actionsEnsim) {
		this.login = login;
		this.login2 = login2;
		this.mdpHash = mdpHash;
		this.uuidUdm = uuidUdm;
		this.civilite = civilite;
		this.nom = nom;
		this.prenom = prenom;
		this.nomjfille = nomjfille;
		this.prononciation = prononciation;
		this.datenaiss = datenaiss;
		this.villenaiss = villenaiss;
		this.dptnaiss = dptnaiss;
		this.paysnaiss = paysnaiss;
		this.nationalite = nationalite;
		this.sitfam = sitfam;
		this.nom1 = nom1;
		this.rue1 = rue1;
		this.cp1 = cp1;
		this.ville1 = ville1;
		this.tel1 = tel1;
		this.fax = fax;
		this.pays1 = pays1;
		this.nom2 = nom2;
		this.rue2 = rue2;
		this.cp2 = cp2;
		this.ville2 = ville2;
		this.tel2 = tel2;
		this.pays2 = pays2;
		this.connaissance = connaissance;
		this.alternance = alternance;
		this.origine = origine;
		this.echangeProgram = echangeProgram;
		this.echangeProfNom = echangeProfNom;
		this.echangeProfFonction = echangeProfFonction;
		this.echangeProfEmail = echangeProfEmail;
		this.candiploNiveau = candiploNiveau;
		this.candiploType = candiploType;
		this.candiploIntitule = candiploIntitule;
		this.filiere = filiere;
		this.concours = concours;
		this.emploi = emploi;
		this.nometa = nometa;
		this.rueeta = rueeta;
		this.cpeta = cpeta;
		this.villeeta = villeeta;
		this.payseta = payseta;
		this.teleta = teleta;
		this.seriebac = seriebac;
		this.mentionbac = mentionbac;
		this.anneebac = anneebac;
		this.lyceebac = lyceebac;
		this.villebac = villebac;
		this.paysbac = paysbac;
		this.bea = bea;
		this.anneesuivibac1 = anneesuivibac1;
		this.anneesuivibac2 = anneesuivibac2;
		this.anneesuivibac3 = anneesuivibac3;
		this.etasuivibac1 = etasuivibac1;
		this.etasuivibac2 = etasuivibac2;
		this.etasuivibac3 = etasuivibac3;
		this.filsuivibac1 = filsuivibac1;
		this.filsuivibac2 = filsuivibac2;
		this.filsuivibac3 = filsuivibac3;
		this.resultatsuivibac1 = resultatsuivibac1;
		this.resultatsuivibac2 = resultatsuivibac2;
		this.resultatsuivibac3 = resultatsuivibac3;
		this.moygesuivibac1 = moygesuivibac1;
		this.moygesuivibac2 = moygesuivibac2;
		this.moygesuivibac3 = moygesuivibac3;
		this.moyangsuivibac1 = moyangsuivibac1;
		this.moyangsuivibac2 = moyangsuivibac2;
		this.moyangsuivibac3 = moyangsuivibac3;
		this.suivibacBreak = suivibacBreak;
		this.stages = stages;
		this.sejours = sejours;
		this.langue1 = langue1;
		this.langue2 = langue2;
		this.langue3 = langue3;
		this.carteid = carteid;
		this.attesdiplome = attesdiplome;
		this.photo = photo;
		this.cv = cv;
		this.cvOk = cvOk;
		this.lettreMotiv = lettreMotiv;
		this.motiv = motiv;
		this.cheque = cheque;
		this.bacPhotocopie = bacPhotocopie;
		this.notes3annees = notes3annees;
		this.avis1 = avis1;
		this.avis2 = avis2;
		this.dossierCampusFrance = dossierCampusFrance;
		this.campusFrance = campusFrance;
		this.dateConstitutionDossier = dateConstitutionDossier;
		this.dateDemandeConfirmationDossier = dateDemandeConfirmationDossier;
		this.valide = valide;
		this.dateConfirmationDossier = dateConfirmationDossier;
		this.abandon = abandon;
		this.abandonMotif = abandonMotif;
		this.dateReceptionImprime = dateReceptionImprime;
		this.dossierRapporteur1 = dossierRapporteur1;
		this.dossierRapporteur2 = dossierRapporteur2;
		this.dossierNote1 = dossierNote1;
		this.dossierNote2 = dossierNote2;
		this.statutDossier = statutDossier;
		this.dateStatutDossier = dateStatutDossier;
		this.notifStatutDossier = notifStatutDossier;
		this.entretienAuditeur1 = entretienAuditeur1;
		this.entretienAuditeur2 = entretienAuditeur2;
		this.entretienSalle = entretienSalle;
		this.entretienHeure = entretienHeure;
		this.entretienNote = entretienNote;
		this.dateChoixSouhaits = dateChoixSouhaits;
		this.dateChoix1 = dateChoix1;
		this.dateChoix2 = dateChoix2;
		this.dateSession = dateSession;
		this.entretienChoixRetenu = entretienChoixRetenu;
		this.dateConvocation = dateConvocation;
		this.dateNotificationConvocation = dateNotificationConvocation;
		this.statutEntretien = statutEntretien;
		this.dateStatutEntretien = dateStatutEntretien;
		this.notifStatutEntretien = notifStatutEntretien;
		this.statutAdmission = statutAdmission;
		this.dateNotifAdmission = dateNotifAdmission;
		this.rang = rang;
		this.statutInscription = statutInscription;
		this.dateStatutInscription = dateStatutInscription;
		this.notifStatutInscription = notifStatutInscription;
		this.dateReceptionInscription = dateReceptionInscription;
		this.dateDerniereConsultation = dateDerniereConsultation;
		this.derniereVisiteAnticollision = derniereVisiteAnticollision;
		this.dateModifAdmin = dateModifAdmin;
		this.nomModifAdmin = nomModifAdmin;
		this.statutDelete = statutDelete;
		this.unlocked = unlocked;
		this.etudiant = etudiant;
		this.boursier = boursier;
		this.numUdm = numUdm;
		this.mailUdm = mailUdm;
		this.mailPro = mailPro;
		this.mailProNew = mailProNew;
		this.mailPerso = mailPerso;
		this.mailPersoNew = mailPersoNew;
		this.mailAutreNew = mailAutreNew;
		this.noMaskedMail = noMaskedMail;
		this.promoEntree = promoEntree;
		this.promo = promo;
		this.optionSpCandi = optionSpCandi;
		this.optionSp = optionSp;
		this.td = td;
		this.tp = tp;
		this.gt1 = gt1;
		this.gt2 = gt2;
		this.gt3 = gt3;
		this.gt4 = gt4;
		this.gt5 = gt5;
		this.gt6 = gt6;
		this.handicap = handicap;
		this.activiteRemuneree = activiteRemuneree;
		this.absencePerm = absencePerm;
		this.absencesLongues = absencesLongues;
		this.ajac = ajac;
		this.redoublant = redoublant;
		this.cursus = cursus;
		this.idEnsApprenti = idEnsApprenti;
		this.matieresIntraorg = matieresIntraorg;
		this.stageFacultatif = stageFacultatif;
		this.relinterDisp = relinterDisp;
		this.toic = toic;
		this.commentaire = commentaire;
		this.reponse = reponse;
		this.anneeCivileEntree = anneeCivileEntree;
		this.anneeCivileSortie = anneeCivileSortie;
		this.anneeCivileDiplome = anneeCivileDiplome;
		this.motifSortie = motifSortie;
		this.photoAlu = photoAlu;
		this.employeurId = employeurId;
		this.employeurSiret = employeurSiret;
		this.employeurApe = employeurApe;
		this.employeurUrl = employeurUrl;
		this.emploiFonction = emploiFonction;
		this.emploiSecteurId = emploiSecteurId;
		this.emploiType1 = emploiType1;
		this.emploiType2 = emploiType2;
		this.emploiMotcleL = emploiMotcleL;
		this.web1 = web1;
		this.web2 = web2;
		this.annuaireInfos = annuaireInfos;
		this.annuaireDiffusion = annuaireDiffusion;
		this.actionsEnsim = actionsEnsim;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getLogin2() {
		return this.login2;
	}

	public void setLogin2(String login2) {
		this.login2 = login2;
	}

	public String getMdpHash() {
		return this.mdpHash;
	}

	public void setMdpHash(String mdpHash) {
		this.mdpHash = mdpHash;
	}

	public String getUuidUdm() {
		return this.uuidUdm;
	}

	public void setUuidUdm(String uuidUdm) {
		this.uuidUdm = uuidUdm;
	}

	public String getCivilite() {
		return this.civilite;
	}

	public void setCivilite(String civilite) {
		this.civilite = civilite;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getNomjfille() {
		return this.nomjfille;
	}

	public void setNomjfille(String nomjfille) {
		this.nomjfille = nomjfille;
	}

	public String getPrononciation() {
		return this.prononciation;
	}

	public void setPrononciation(String prononciation) {
		this.prononciation = prononciation;
	}

	public Date getDatenaiss() {
		return this.datenaiss;
	}

	public void setDatenaiss(Date datenaiss) {
		this.datenaiss = datenaiss;
	}

	public String getVillenaiss() {
		return this.villenaiss;
	}

	public void setVillenaiss(String villenaiss) {
		this.villenaiss = villenaiss;
	}

	public String getDptnaiss() {
		return this.dptnaiss;
	}

	public void setDptnaiss(String dptnaiss) {
		this.dptnaiss = dptnaiss;
	}

	public String getPaysnaiss() {
		return this.paysnaiss;
	}

	public void setPaysnaiss(String paysnaiss) {
		this.paysnaiss = paysnaiss;
	}

	public String getNationalite() {
		return this.nationalite;
	}

	public void setNationalite(String nationalite) {
		this.nationalite = nationalite;
	}

	public String getSitfam() {
		return this.sitfam;
	}

	public void setSitfam(String sitfam) {
		this.sitfam = sitfam;
	}

	public String getNom1() {
		return this.nom1;
	}

	public void setNom1(String nom1) {
		this.nom1 = nom1;
	}

	public String getRue1() {
		return this.rue1;
	}

	public void setRue1(String rue1) {
		this.rue1 = rue1;
	}

	public String getCp1() {
		return this.cp1;
	}

	public void setCp1(String cp1) {
		this.cp1 = cp1;
	}

	public String getVille1() {
		return this.ville1;
	}

	public void setVille1(String ville1) {
		this.ville1 = ville1;
	}

	public String getTel1() {
		return this.tel1;
	}

	public void setTel1(String tel1) {
		this.tel1 = tel1;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getPays1() {
		return this.pays1;
	}

	public void setPays1(String pays1) {
		this.pays1 = pays1;
	}

	public String getNom2() {
		return this.nom2;
	}

	public void setNom2(String nom2) {
		this.nom2 = nom2;
	}

	public String getRue2() {
		return this.rue2;
	}

	public void setRue2(String rue2) {
		this.rue2 = rue2;
	}

	public String getCp2() {
		return this.cp2;
	}

	public void setCp2(String cp2) {
		this.cp2 = cp2;
	}

	public String getVille2() {
		return this.ville2;
	}

	public void setVille2(String ville2) {
		this.ville2 = ville2;
	}

	public String getTel2() {
		return this.tel2;
	}

	public void setTel2(String tel2) {
		this.tel2 = tel2;
	}

	public String getPays2() {
		return this.pays2;
	}

	public void setPays2(String pays2) {
		this.pays2 = pays2;
	}

	public String getConnaissance() {
		return this.connaissance;
	}

	public void setConnaissance(String connaissance) {
		this.connaissance = connaissance;
	}

	public byte getAlternance() {
		return this.alternance;
	}

	public void setAlternance(byte alternance) {
		this.alternance = alternance;
	}

	public String getOrigine() {
		return this.origine;
	}

	public void setOrigine(String origine) {
		this.origine = origine;
	}

	public String getEchangeProgram() {
		return this.echangeProgram;
	}

	public void setEchangeProgram(String echangeProgram) {
		this.echangeProgram = echangeProgram;
	}

	public String getEchangeProfNom() {
		return this.echangeProfNom;
	}

	public void setEchangeProfNom(String echangeProfNom) {
		this.echangeProfNom = echangeProfNom;
	}

	public String getEchangeProfFonction() {
		return this.echangeProfFonction;
	}

	public void setEchangeProfFonction(String echangeProfFonction) {
		this.echangeProfFonction = echangeProfFonction;
	}

	public String getEchangeProfEmail() {
		return this.echangeProfEmail;
	}

	public void setEchangeProfEmail(String echangeProfEmail) {
		this.echangeProfEmail = echangeProfEmail;
	}

	public String getCandiploNiveau() {
		return this.candiploNiveau;
	}

	public void setCandiploNiveau(String candiploNiveau) {
		this.candiploNiveau = candiploNiveau;
	}

	public String getCandiploType() {
		return this.candiploType;
	}

	public void setCandiploType(String candiploType) {
		this.candiploType = candiploType;
	}

	public String getCandiploIntitule() {
		return this.candiploIntitule;
	}

	public void setCandiploIntitule(String candiploIntitule) {
		this.candiploIntitule = candiploIntitule;
	}

	public String getFiliere() {
		return this.filiere;
	}

	public void setFiliere(String filiere) {
		this.filiere = filiere;
	}

	public String getConcours() {
		return this.concours;
	}

	public void setConcours(String concours) {
		this.concours = concours;
	}

	public String getEmploi() {
		return this.emploi;
	}

	public void setEmploi(String emploi) {
		this.emploi = emploi;
	}

	public String getNometa() {
		return this.nometa;
	}

	public void setNometa(String nometa) {
		this.nometa = nometa;
	}

	public String getRueeta() {
		return this.rueeta;
	}

	public void setRueeta(String rueeta) {
		this.rueeta = rueeta;
	}

	public String getCpeta() {
		return this.cpeta;
	}

	public void setCpeta(String cpeta) {
		this.cpeta = cpeta;
	}

	public String getVilleeta() {
		return this.villeeta;
	}

	public void setVilleeta(String villeeta) {
		this.villeeta = villeeta;
	}

	public String getPayseta() {
		return this.payseta;
	}

	public void setPayseta(String payseta) {
		this.payseta = payseta;
	}

	public String getTeleta() {
		return this.teleta;
	}

	public void setTeleta(String teleta) {
		this.teleta = teleta;
	}

	public String getSeriebac() {
		return this.seriebac;
	}

	public void setSeriebac(String seriebac) {
		this.seriebac = seriebac;
	}

	public String getMentionbac() {
		return this.mentionbac;
	}

	public void setMentionbac(String mentionbac) {
		this.mentionbac = mentionbac;
	}

	public String getAnneebac() {
		return this.anneebac;
	}

	public void setAnneebac(String anneebac) {
		this.anneebac = anneebac;
	}

	public String getLyceebac() {
		return this.lyceebac;
	}

	public void setLyceebac(String lyceebac) {
		this.lyceebac = lyceebac;
	}

	public String getVillebac() {
		return this.villebac;
	}

	public void setVillebac(String villebac) {
		this.villebac = villebac;
	}

	public String getPaysbac() {
		return this.paysbac;
	}

	public void setPaysbac(String paysbac) {
		this.paysbac = paysbac;
	}

	public String getBea() {
		return this.bea;
	}

	public void setBea(String bea) {
		this.bea = bea;
	}

	public String getAnneesuivibac1() {
		return this.anneesuivibac1;
	}

	public void setAnneesuivibac1(String anneesuivibac1) {
		this.anneesuivibac1 = anneesuivibac1;
	}

	public String getAnneesuivibac2() {
		return this.anneesuivibac2;
	}

	public void setAnneesuivibac2(String anneesuivibac2) {
		this.anneesuivibac2 = anneesuivibac2;
	}

	public String getAnneesuivibac3() {
		return this.anneesuivibac3;
	}

	public void setAnneesuivibac3(String anneesuivibac3) {
		this.anneesuivibac3 = anneesuivibac3;
	}

	public String getEtasuivibac1() {
		return this.etasuivibac1;
	}

	public void setEtasuivibac1(String etasuivibac1) {
		this.etasuivibac1 = etasuivibac1;
	}

	public String getEtasuivibac2() {
		return this.etasuivibac2;
	}

	public void setEtasuivibac2(String etasuivibac2) {
		this.etasuivibac2 = etasuivibac2;
	}

	public String getEtasuivibac3() {
		return this.etasuivibac3;
	}

	public void setEtasuivibac3(String etasuivibac3) {
		this.etasuivibac3 = etasuivibac3;
	}

	public String getFilsuivibac1() {
		return this.filsuivibac1;
	}

	public void setFilsuivibac1(String filsuivibac1) {
		this.filsuivibac1 = filsuivibac1;
	}

	public String getFilsuivibac2() {
		return this.filsuivibac2;
	}

	public void setFilsuivibac2(String filsuivibac2) {
		this.filsuivibac2 = filsuivibac2;
	}

	public String getFilsuivibac3() {
		return this.filsuivibac3;
	}

	public void setFilsuivibac3(String filsuivibac3) {
		this.filsuivibac3 = filsuivibac3;
	}

	public String getResultatsuivibac1() {
		return this.resultatsuivibac1;
	}

	public void setResultatsuivibac1(String resultatsuivibac1) {
		this.resultatsuivibac1 = resultatsuivibac1;
	}

	public String getResultatsuivibac2() {
		return this.resultatsuivibac2;
	}

	public void setResultatsuivibac2(String resultatsuivibac2) {
		this.resultatsuivibac2 = resultatsuivibac2;
	}

	public String getResultatsuivibac3() {
		return this.resultatsuivibac3;
	}

	public void setResultatsuivibac3(String resultatsuivibac3) {
		this.resultatsuivibac3 = resultatsuivibac3;
	}

	public String getMoygesuivibac1() {
		return this.moygesuivibac1;
	}

	public void setMoygesuivibac1(String moygesuivibac1) {
		this.moygesuivibac1 = moygesuivibac1;
	}

	public String getMoygesuivibac2() {
		return this.moygesuivibac2;
	}

	public void setMoygesuivibac2(String moygesuivibac2) {
		this.moygesuivibac2 = moygesuivibac2;
	}

	public String getMoygesuivibac3() {
		return this.moygesuivibac3;
	}

	public void setMoygesuivibac3(String moygesuivibac3) {
		this.moygesuivibac3 = moygesuivibac3;
	}

	public String getMoyangsuivibac1() {
		return this.moyangsuivibac1;
	}

	public void setMoyangsuivibac1(String moyangsuivibac1) {
		this.moyangsuivibac1 = moyangsuivibac1;
	}

	public String getMoyangsuivibac2() {
		return this.moyangsuivibac2;
	}

	public void setMoyangsuivibac2(String moyangsuivibac2) {
		this.moyangsuivibac2 = moyangsuivibac2;
	}

	public String getMoyangsuivibac3() {
		return this.moyangsuivibac3;
	}

	public void setMoyangsuivibac3(String moyangsuivibac3) {
		this.moyangsuivibac3 = moyangsuivibac3;
	}

	public String getSuivibacBreak() {
		return this.suivibacBreak;
	}

	public void setSuivibacBreak(String suivibacBreak) {
		this.suivibacBreak = suivibacBreak;
	}

	public byte[] getStages() {
		return this.stages;
	}

	public void setStages(byte[] stages) {
		this.stages = stages;
	}

	public byte[] getSejours() {
		return this.sejours;
	}

	public void setSejours(byte[] sejours) {
		this.sejours = sejours;
	}

	public String getLangue1() {
		return this.langue1;
	}

	public void setLangue1(String langue1) {
		this.langue1 = langue1;
	}

	public String getLangue2() {
		return this.langue2;
	}

	public void setLangue2(String langue2) {
		this.langue2 = langue2;
	}

	public String getLangue3() {
		return this.langue3;
	}

	public void setLangue3(String langue3) {
		this.langue3 = langue3;
	}

	public String getCarteid() {
		return this.carteid;
	}

	public void setCarteid(String carteid) {
		this.carteid = carteid;
	}

	public String getAttesdiplome() {
		return this.attesdiplome;
	}

	public void setAttesdiplome(String attesdiplome) {
		this.attesdiplome = attesdiplome;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getCv() {
		return this.cv;
	}

	public void setCv(String cv) {
		this.cv = cv;
	}

	public String getCvOk() {
		return this.cvOk;
	}

	public void setCvOk(String cvOk) {
		this.cvOk = cvOk;
	}

	public String getLettreMotiv() {
		return this.lettreMotiv;
	}

	public void setLettreMotiv(String lettreMotiv) {
		this.lettreMotiv = lettreMotiv;
	}

	public String getMotiv() {
		return this.motiv;
	}

	public void setMotiv(String motiv) {
		this.motiv = motiv;
	}

	public String getCheque() {
		return this.cheque;
	}

	public void setCheque(String cheque) {
		this.cheque = cheque;
	}

	public String getBacPhotocopie() {
		return this.bacPhotocopie;
	}

	public void setBacPhotocopie(String bacPhotocopie) {
		this.bacPhotocopie = bacPhotocopie;
	}

	public String getNotes3annees() {
		return this.notes3annees;
	}

	public void setNotes3annees(String notes3annees) {
		this.notes3annees = notes3annees;
	}

	public String getAvis1() {
		return this.avis1;
	}

	public void setAvis1(String avis1) {
		this.avis1 = avis1;
	}

	public String getAvis2() {
		return this.avis2;
	}

	public void setAvis2(String avis2) {
		this.avis2 = avis2;
	}

	public String getDossierCampusFrance() {
		return this.dossierCampusFrance;
	}

	public void setDossierCampusFrance(String dossierCampusFrance) {
		this.dossierCampusFrance = dossierCampusFrance;
	}

	public String getCampusFrance() {
		return this.campusFrance;
	}

	public void setCampusFrance(String campusFrance) {
		this.campusFrance = campusFrance;
	}

	public Date getDateConstitutionDossier() {
		return this.dateConstitutionDossier;
	}

	public void setDateConstitutionDossier(Date dateConstitutionDossier) {
		this.dateConstitutionDossier = dateConstitutionDossier;
	}

	public Date getDateDemandeConfirmationDossier() {
		return this.dateDemandeConfirmationDossier;
	}

	public void setDateDemandeConfirmationDossier(
			Date dateDemandeConfirmationDossier) {
		this.dateDemandeConfirmationDossier = dateDemandeConfirmationDossier;
	}

	public byte getValide() {
		return this.valide;
	}

	public void setValide(byte valide) {
		this.valide = valide;
	}

	public Date getDateConfirmationDossier() {
		return this.dateConfirmationDossier;
	}

	public void setDateConfirmationDossier(Date dateConfirmationDossier) {
		this.dateConfirmationDossier = dateConfirmationDossier;
	}

	public byte getAbandon() {
		return this.abandon;
	}

	public void setAbandon(byte abandon) {
		this.abandon = abandon;
	}

	public String getAbandonMotif() {
		return this.abandonMotif;
	}

	public void setAbandonMotif(String abandonMotif) {
		this.abandonMotif = abandonMotif;
	}

	public Date getDateReceptionImprime() {
		return this.dateReceptionImprime;
	}

	public void setDateReceptionImprime(Date dateReceptionImprime) {
		this.dateReceptionImprime = dateReceptionImprime;
	}

	public String getDossierRapporteur1() {
		return this.dossierRapporteur1;
	}

	public void setDossierRapporteur1(String dossierRapporteur1) {
		this.dossierRapporteur1 = dossierRapporteur1;
	}

	public String getDossierRapporteur2() {
		return this.dossierRapporteur2;
	}

	public void setDossierRapporteur2(String dossierRapporteur2) {
		this.dossierRapporteur2 = dossierRapporteur2;
	}

	public int getDossierNote1() {
		return this.dossierNote1;
	}

	public void setDossierNote1(int dossierNote1) {
		this.dossierNote1 = dossierNote1;
	}

	public int getDossierNote2() {
		return this.dossierNote2;
	}

	public void setDossierNote2(int dossierNote2) {
		this.dossierNote2 = dossierNote2;
	}

	public String getStatutDossier() {
		return this.statutDossier;
	}

	public void setStatutDossier(String statutDossier) {
		this.statutDossier = statutDossier;
	}

	public Date getDateStatutDossier() {
		return this.dateStatutDossier;
	}

	public void setDateStatutDossier(Date dateStatutDossier) {
		this.dateStatutDossier = dateStatutDossier;
	}

	public byte getNotifStatutDossier() {
		return this.notifStatutDossier;
	}

	public void setNotifStatutDossier(byte notifStatutDossier) {
		this.notifStatutDossier = notifStatutDossier;
	}

	public String getEntretienAuditeur1() {
		return this.entretienAuditeur1;
	}

	public void setEntretienAuditeur1(String entretienAuditeur1) {
		this.entretienAuditeur1 = entretienAuditeur1;
	}

	public String getEntretienAuditeur2() {
		return this.entretienAuditeur2;
	}

	public void setEntretienAuditeur2(String entretienAuditeur2) {
		this.entretienAuditeur2 = entretienAuditeur2;
	}

	public String getEntretienSalle() {
		return this.entretienSalle;
	}

	public void setEntretienSalle(String entretienSalle) {
		this.entretienSalle = entretienSalle;
	}

	public String getEntretienHeure() {
		return this.entretienHeure;
	}

	public void setEntretienHeure(String entretienHeure) {
		this.entretienHeure = entretienHeure;
	}

	public int getEntretienNote() {
		return this.entretienNote;
	}

	public void setEntretienNote(int entretienNote) {
		this.entretienNote = entretienNote;
	}

	public Date getDateChoixSouhaits() {
		return this.dateChoixSouhaits;
	}

	public void setDateChoixSouhaits(Date dateChoixSouhaits) {
		this.dateChoixSouhaits = dateChoixSouhaits;
	}

	public Date getDateChoix1() {
		return this.dateChoix1;
	}

	public void setDateChoix1(Date dateChoix1) {
		this.dateChoix1 = dateChoix1;
	}

	public Date getDateChoix2() {
		return this.dateChoix2;
	}

	public void setDateChoix2(Date dateChoix2) {
		this.dateChoix2 = dateChoix2;
	}

	public Date getDateSession() {
		return this.dateSession;
	}

	public void setDateSession(Date dateSession) {
		this.dateSession = dateSession;
	}

	public String getEntretienChoixRetenu() {
		return this.entretienChoixRetenu;
	}

	public void setEntretienChoixRetenu(String entretienChoixRetenu) {
		this.entretienChoixRetenu = entretienChoixRetenu;
	}

	public Date getDateConvocation() {
		return this.dateConvocation;
	}

	public void setDateConvocation(Date dateConvocation) {
		this.dateConvocation = dateConvocation;
	}

	public Date getDateNotificationConvocation() {
		return this.dateNotificationConvocation;
	}

	public void setDateNotificationConvocation(Date dateNotificationConvocation) {
		this.dateNotificationConvocation = dateNotificationConvocation;
	}

	public String getStatutEntretien() {
		return this.statutEntretien;
	}

	public void setStatutEntretien(String statutEntretien) {
		this.statutEntretien = statutEntretien;
	}

	public Date getDateStatutEntretien() {
		return this.dateStatutEntretien;
	}

	public void setDateStatutEntretien(Date dateStatutEntretien) {
		this.dateStatutEntretien = dateStatutEntretien;
	}

	public byte getNotifStatutEntretien() {
		return this.notifStatutEntretien;
	}

	public void setNotifStatutEntretien(byte notifStatutEntretien) {
		this.notifStatutEntretien = notifStatutEntretien;
	}

	public String getStatutAdmission() {
		return this.statutAdmission;
	}

	public void setStatutAdmission(String statutAdmission) {
		this.statutAdmission = statutAdmission;
	}

	public Date getDateNotifAdmission() {
		return this.dateNotifAdmission;
	}

	public void setDateNotifAdmission(Date dateNotifAdmission) {
		this.dateNotifAdmission = dateNotifAdmission;
	}

	public short getRang() {
		return this.rang;
	}

	public void setRang(short rang) {
		this.rang = rang;
	}

	public String getStatutInscription() {
		return this.statutInscription;
	}

	public void setStatutInscription(String statutInscription) {
		this.statutInscription = statutInscription;
	}

	public Date getDateStatutInscription() {
		return this.dateStatutInscription;
	}

	public void setDateStatutInscription(Date dateStatutInscription) {
		this.dateStatutInscription = dateStatutInscription;
	}

	public byte getNotifStatutInscription() {
		return this.notifStatutInscription;
	}

	public void setNotifStatutInscription(byte notifStatutInscription) {
		this.notifStatutInscription = notifStatutInscription;
	}

	public Date getDateReceptionInscription() {
		return this.dateReceptionInscription;
	}

	public void setDateReceptionInscription(Date dateReceptionInscription) {
		this.dateReceptionInscription = dateReceptionInscription;
	}

	public Date getDateDerniereConsultation() {
		return this.dateDerniereConsultation;
	}

	public void setDateDerniereConsultation(Date dateDerniereConsultation) {
		this.dateDerniereConsultation = dateDerniereConsultation;
	}

	public String getDerniereVisiteAnticollision() {
		return this.derniereVisiteAnticollision;
	}

	public void setDerniereVisiteAnticollision(
			String derniereVisiteAnticollision) {
		this.derniereVisiteAnticollision = derniereVisiteAnticollision;
	}

	public Date getDateModifAdmin() {
		return this.dateModifAdmin;
	}

	public void setDateModifAdmin(Date dateModifAdmin) {
		this.dateModifAdmin = dateModifAdmin;
	}

	public String getNomModifAdmin() {
		return this.nomModifAdmin;
	}

	public void setNomModifAdmin(String nomModifAdmin) {
		this.nomModifAdmin = nomModifAdmin;
	}

	public byte getStatutDelete() {
		return this.statutDelete;
	}

	public void setStatutDelete(byte statutDelete) {
		this.statutDelete = statutDelete;
	}

	public byte getUnlocked() {
		return this.unlocked;
	}

	public void setUnlocked(byte unlocked) {
		this.unlocked = unlocked;
	}

	public String getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(String etudiant) {
		this.etudiant = etudiant;
	}

	public String getBoursier() {
		return this.boursier;
	}

	public void setBoursier(String boursier) {
		this.boursier = boursier;
	}

	public String getNumUdm() {
		return this.numUdm;
	}

	public void setNumUdm(String numUdm) {
		this.numUdm = numUdm;
	}

	public String getMailUdm() {
		return this.mailUdm;
	}

	public void setMailUdm(String mailUdm) {
		this.mailUdm = mailUdm;
	}

	public String getMailPro() {
		return this.mailPro;
	}

	public void setMailPro(String mailPro) {
		this.mailPro = mailPro;
	}

	public String getMailProNew() {
		return this.mailProNew;
	}

	public void setMailProNew(String mailProNew) {
		this.mailProNew = mailProNew;
	}

	public String getMailPerso() {
		return this.mailPerso;
	}

	public void setMailPerso(String mailPerso) {
		this.mailPerso = mailPerso;
	}

	public String getMailPersoNew() {
		return this.mailPersoNew;
	}

	public void setMailPersoNew(String mailPersoNew) {
		this.mailPersoNew = mailPersoNew;
	}

	public String getMailAutreNew() {
		return this.mailAutreNew;
	}

	public void setMailAutreNew(String mailAutreNew) {
		this.mailAutreNew = mailAutreNew;
	}

	public byte getNoMaskedMail() {
		return this.noMaskedMail;
	}

	public void setNoMaskedMail(byte noMaskedMail) {
		this.noMaskedMail = noMaskedMail;
	}

	public String getPromoEntree() {
		return this.promoEntree;
	}

	public void setPromoEntree(String promoEntree) {
		this.promoEntree = promoEntree;
	}

	public String getPromo() {
		return this.promo;
	}

	public void setPromo(String promo) {
		this.promo = promo;
	}

	public String getOptionSpCandi() {
		return this.optionSpCandi;
	}

	public void setOptionSpCandi(String optionSpCandi) {
		this.optionSpCandi = optionSpCandi;
	}

	public String getOptionSp() {
		return this.optionSp;
	}

	public void setOptionSp(String optionSp) {
		this.optionSp = optionSp;
	}

	public String getTd() {
		return this.td;
	}

	public void setTd(String td) {
		this.td = td;
	}

	public String getTp() {
		return this.tp;
	}

	public void setTp(String tp) {
		this.tp = tp;
	}

	public String getGt1() {
		return this.gt1;
	}

	public void setGt1(String gt1) {
		this.gt1 = gt1;
	}

	public String getGt2() {
		return this.gt2;
	}

	public void setGt2(String gt2) {
		this.gt2 = gt2;
	}

	public String getGt3() {
		return this.gt3;
	}

	public void setGt3(String gt3) {
		this.gt3 = gt3;
	}

	public String getGt4() {
		return this.gt4;
	}

	public void setGt4(String gt4) {
		this.gt4 = gt4;
	}

	public String getGt5() {
		return this.gt5;
	}

	public void setGt5(String gt5) {
		this.gt5 = gt5;
	}

	public String getGt6() {
		return this.gt6;
	}

	public void setGt6(String gt6) {
		this.gt6 = gt6;
	}

	public String getHandicap() {
		return this.handicap;
	}

	public void setHandicap(String handicap) {
		this.handicap = handicap;
	}

	public String getActiviteRemuneree() {
		return this.activiteRemuneree;
	}

	public void setActiviteRemuneree(String activiteRemuneree) {
		this.activiteRemuneree = activiteRemuneree;
	}

	public String getAbsencePerm() {
		return this.absencePerm;
	}

	public void setAbsencePerm(String absencePerm) {
		this.absencePerm = absencePerm;
	}

	public String getAbsencesLongues() {
		return this.absencesLongues;
	}

	public void setAbsencesLongues(String absencesLongues) {
		this.absencesLongues = absencesLongues;
	}

	public byte getAjac() {
		return this.ajac;
	}

	public void setAjac(byte ajac) {
		this.ajac = ajac;
	}

	public String getRedoublant() {
		return this.redoublant;
	}

	public void setRedoublant(String redoublant) {
		this.redoublant = redoublant;
	}

	public String getCursus() {
		return this.cursus;
	}

	public void setCursus(String cursus) {
		this.cursus = cursus;
	}

	public short getIdEnsApprenti() {
		return this.idEnsApprenti;
	}

	public void setIdEnsApprenti(short idEnsApprenti) {
		this.idEnsApprenti = idEnsApprenti;
	}

	public String getMatieresIntraorg() {
		return this.matieresIntraorg;
	}

	public void setMatieresIntraorg(String matieresIntraorg) {
		this.matieresIntraorg = matieresIntraorg;
	}

	public char getStageFacultatif() {
		return this.stageFacultatif;
	}

	public void setStageFacultatif(char stageFacultatif) {
		this.stageFacultatif = stageFacultatif;
	}

	public String getRelinterDisp() {
		return this.relinterDisp;
	}

	public void setRelinterDisp(String relinterDisp) {
		this.relinterDisp = relinterDisp;
	}

	public String getToic() {
		return this.toic;
	}

	public void setToic(String toic) {
		this.toic = toic;
	}

	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	public String getReponse() {
		return this.reponse;
	}

	public void setReponse(String reponse) {
		this.reponse = reponse;
	}

	public String getAnneeCivileEntree() {
		return this.anneeCivileEntree;
	}

	public void setAnneeCivileEntree(String anneeCivileEntree) {
		this.anneeCivileEntree = anneeCivileEntree;
	}

	public String getAnneeCivileSortie() {
		return this.anneeCivileSortie;
	}

	public void setAnneeCivileSortie(String anneeCivileSortie) {
		this.anneeCivileSortie = anneeCivileSortie;
	}

	public String getAnneeCivileDiplome() {
		return this.anneeCivileDiplome;
	}

	public void setAnneeCivileDiplome(String anneeCivileDiplome) {
		this.anneeCivileDiplome = anneeCivileDiplome;
	}

	public char getMotifSortie() {
		return this.motifSortie;
	}

	public void setMotifSortie(char motifSortie) {
		this.motifSortie = motifSortie;
	}

	public String getPhotoAlu() {
		return this.photoAlu;
	}

	public void setPhotoAlu(String photoAlu) {
		this.photoAlu = photoAlu;
	}

	public int getEmployeurId() {
		return this.employeurId;
	}

	public void setEmployeurId(int employeurId) {
		this.employeurId = employeurId;
	}

	public String getEmployeurSiret() {
		return this.employeurSiret;
	}

	public void setEmployeurSiret(String employeurSiret) {
		this.employeurSiret = employeurSiret;
	}

	public String getEmployeurApe() {
		return this.employeurApe;
	}

	public void setEmployeurApe(String employeurApe) {
		this.employeurApe = employeurApe;
	}

	public String getEmployeurUrl() {
		return this.employeurUrl;
	}

	public void setEmployeurUrl(String employeurUrl) {
		this.employeurUrl = employeurUrl;
	}

	public String getEmploiFonction() {
		return this.emploiFonction;
	}

	public void setEmploiFonction(String emploiFonction) {
		this.emploiFonction = emploiFonction;
	}

	public byte getEmploiSecteurId() {
		return this.emploiSecteurId;
	}

	public void setEmploiSecteurId(byte emploiSecteurId) {
		this.emploiSecteurId = emploiSecteurId;
	}

	public byte getEmploiType1() {
		return this.emploiType1;
	}

	public void setEmploiType1(byte emploiType1) {
		this.emploiType1 = emploiType1;
	}

	public byte getEmploiType2() {
		return this.emploiType2;
	}

	public void setEmploiType2(byte emploiType2) {
		this.emploiType2 = emploiType2;
	}

	public String getEmploiMotcleL() {
		return this.emploiMotcleL;
	}

	public void setEmploiMotcleL(String emploiMotcleL) {
		this.emploiMotcleL = emploiMotcleL;
	}

	public String getWeb1() {
		return this.web1;
	}

	public void setWeb1(String web1) {
		this.web1 = web1;
	}

	public String getWeb2() {
		return this.web2;
	}

	public void setWeb2(String web2) {
		this.web2 = web2;
	}

	public String getAnnuaireInfos() {
		return this.annuaireInfos;
	}

	public void setAnnuaireInfos(String annuaireInfos) {
		this.annuaireInfos = annuaireInfos;
	}

	public String getAnnuaireDiffusion() {
		return this.annuaireDiffusion;
	}

	public void setAnnuaireDiffusion(String annuaireDiffusion) {
		this.annuaireDiffusion = annuaireDiffusion;
	}

	public String getActionsEnsim() {
		return this.actionsEnsim;
	}

	public void setActionsEnsim(String actionsEnsim) {
		this.actionsEnsim = actionsEnsim;
	}

}
