package com.abstix.dao;

// Generated 23 nov. 2015 11:36:31 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Personnels generated by hbm2java
 */
public class Personnels implements java.io.Serializable {

	private Integer id;
	private String pass;
	private byte nosend;
	private byte verrou;
	private String alias;
	private String civilite;
	private String nom;
	private String prenom;
	private Date dateNaiss;
	private String identifiant;
	private String harpege;
	private String numInsee;
	private String photo;
	private String courriel;
	private String adressePerso;
	private String urlPerso;
	private String paysPerso;
	private String adressePro;
	private String paysPro;
	private String telPerso1;
	private String telPerso2;
	private String telPro1;
	private String telPro2;
	private String bureau;
	private String cleSalle;
	private String courrielPro;
	private String courrielPro2;
	private String faxPro;
	private String urlPro;
	private String duree;
	private String emploiPrincipal;
	private String statut;
	private String fonction;
	private String responsabilites;
	private String referent;
	private String employeur;
	private byte labo;
	private Date dateFin;
	private String remarquesAdmin;
	private String remarquesPerso;
	private String auteurModif;
	private Date dateModif;
	private Date dateConnexion;
	private byte del;
	private String ensCompetences;
	private byte activiteEns;
	private byte activiteRech;
	private byte activiteAdmin;
	private byte activiteTechn;
	private byte activiteAutre;

	public Personnels() {
	}

	public Personnels(String pass, byte nosend, byte verrou, String alias,
			String civilite, String nom, String prenom, Date dateNaiss,
			String identifiant, String harpege, String numInsee, String photo,
			String courriel, String adressePerso, String urlPerso,
			String paysPerso, String adressePro, String paysPro,
			String telPerso1, String telPerso2, String telPro1, String telPro2,
			String bureau, String cleSalle, String courrielPro,
			String courrielPro2, String faxPro, String urlPro, String duree,
			String fonction, String responsabilites, String referent,
			byte labo, Date dateFin, String remarquesAdmin,
			String remarquesPerso, String auteurModif, Date dateModif,
			Date dateConnexion, byte del, String ensCompetences,
			byte activiteEns, byte activiteRech, byte activiteAdmin,
			byte activiteTechn, byte activiteAutre) {
		this.pass = pass;
		this.nosend = nosend;
		this.verrou = verrou;
		this.alias = alias;
		this.civilite = civilite;
		this.nom = nom;
		this.prenom = prenom;
		this.dateNaiss = dateNaiss;
		this.identifiant = identifiant;
		this.harpege = harpege;
		this.numInsee = numInsee;
		this.photo = photo;
		this.courriel = courriel;
		this.adressePerso = adressePerso;
		this.urlPerso = urlPerso;
		this.paysPerso = paysPerso;
		this.adressePro = adressePro;
		this.paysPro = paysPro;
		this.telPerso1 = telPerso1;
		this.telPerso2 = telPerso2;
		this.telPro1 = telPro1;
		this.telPro2 = telPro2;
		this.bureau = bureau;
		this.cleSalle = cleSalle;
		this.courrielPro = courrielPro;
		this.courrielPro2 = courrielPro2;
		this.faxPro = faxPro;
		this.urlPro = urlPro;
		this.duree = duree;
		this.fonction = fonction;
		this.responsabilites = responsabilites;
		this.referent = referent;
		this.labo = labo;
		this.dateFin = dateFin;
		this.remarquesAdmin = remarquesAdmin;
		this.remarquesPerso = remarquesPerso;
		this.auteurModif = auteurModif;
		this.dateModif = dateModif;
		this.dateConnexion = dateConnexion;
		this.del = del;
		this.ensCompetences = ensCompetences;
		this.activiteEns = activiteEns;
		this.activiteRech = activiteRech;
		this.activiteAdmin = activiteAdmin;
		this.activiteTechn = activiteTechn;
		this.activiteAutre = activiteAutre;
	}

	public Personnels(String pass, byte nosend, byte verrou, String alias,
			String civilite, String nom, String prenom, Date dateNaiss,
			String identifiant, String harpege, String numInsee, String photo,
			String courriel, String adressePerso, String urlPerso,
			String paysPerso, String adressePro, String paysPro,
			String telPerso1, String telPerso2, String telPro1, String telPro2,
			String bureau, String cleSalle, String courrielPro,
			String courrielPro2, String faxPro, String urlPro, String duree,
			String emploiPrincipal, String statut, String fonction,
			String responsabilites, String referent, String employeur,
			byte labo, Date dateFin, String remarquesAdmin,
			String remarquesPerso, String auteurModif, Date dateModif,
			Date dateConnexion, byte del, String ensCompetences,
			byte activiteEns, byte activiteRech, byte activiteAdmin,
			byte activiteTechn, byte activiteAutre) {
		this.pass = pass;
		this.nosend = nosend;
		this.verrou = verrou;
		this.alias = alias;
		this.civilite = civilite;
		this.nom = nom;
		this.prenom = prenom;
		this.dateNaiss = dateNaiss;
		this.identifiant = identifiant;
		this.harpege = harpege;
		this.numInsee = numInsee;
		this.photo = photo;
		this.courriel = courriel;
		this.adressePerso = adressePerso;
		this.urlPerso = urlPerso;
		this.paysPerso = paysPerso;
		this.adressePro = adressePro;
		this.paysPro = paysPro;
		this.telPerso1 = telPerso1;
		this.telPerso2 = telPerso2;
		this.telPro1 = telPro1;
		this.telPro2 = telPro2;
		this.bureau = bureau;
		this.cleSalle = cleSalle;
		this.courrielPro = courrielPro;
		this.courrielPro2 = courrielPro2;
		this.faxPro = faxPro;
		this.urlPro = urlPro;
		this.duree = duree;
		this.emploiPrincipal = emploiPrincipal;
		this.statut = statut;
		this.fonction = fonction;
		this.responsabilites = responsabilites;
		this.referent = referent;
		this.employeur = employeur;
		this.labo = labo;
		this.dateFin = dateFin;
		this.remarquesAdmin = remarquesAdmin;
		this.remarquesPerso = remarquesPerso;
		this.auteurModif = auteurModif;
		this.dateModif = dateModif;
		this.dateConnexion = dateConnexion;
		this.del = del;
		this.ensCompetences = ensCompetences;
		this.activiteEns = activiteEns;
		this.activiteRech = activiteRech;
		this.activiteAdmin = activiteAdmin;
		this.activiteTechn = activiteTechn;
		this.activiteAutre = activiteAutre;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public byte getNosend() {
		return this.nosend;
	}

	public void setNosend(byte nosend) {
		this.nosend = nosend;
	}

	public byte getVerrou() {
		return this.verrou;
	}

	public void setVerrou(byte verrou) {
		this.verrou = verrou;
	}

	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	public String getCivilite() {
		return this.civilite;
	}

	public void setCivilite(String civilite) {
		this.civilite = civilite;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public Date getDateNaiss() {
		return this.dateNaiss;
	}

	public void setDateNaiss(Date dateNaiss) {
		this.dateNaiss = dateNaiss;
	}

	public String getIdentifiant() {
		return this.identifiant;
	}

	public void setIdentifiant(String identifiant) {
		this.identifiant = identifiant;
	}

	public String getHarpege() {
		return this.harpege;
	}

	public void setHarpege(String harpege) {
		this.harpege = harpege;
	}

	public String getNumInsee() {
		return this.numInsee;
	}

	public void setNumInsee(String numInsee) {
		this.numInsee = numInsee;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getCourriel() {
		return this.courriel;
	}

	public void setCourriel(String courriel) {
		this.courriel = courriel;
	}

	public String getAdressePerso() {
		return this.adressePerso;
	}

	public void setAdressePerso(String adressePerso) {
		this.adressePerso = adressePerso;
	}

	public String getUrlPerso() {
		return this.urlPerso;
	}

	public void setUrlPerso(String urlPerso) {
		this.urlPerso = urlPerso;
	}

	public String getPaysPerso() {
		return this.paysPerso;
	}

	public void setPaysPerso(String paysPerso) {
		this.paysPerso = paysPerso;
	}

	public String getAdressePro() {
		return this.adressePro;
	}

	public void setAdressePro(String adressePro) {
		this.adressePro = adressePro;
	}

	public String getPaysPro() {
		return this.paysPro;
	}

	public void setPaysPro(String paysPro) {
		this.paysPro = paysPro;
	}

	public String getTelPerso1() {
		return this.telPerso1;
	}

	public void setTelPerso1(String telPerso1) {
		this.telPerso1 = telPerso1;
	}

	public String getTelPerso2() {
		return this.telPerso2;
	}

	public void setTelPerso2(String telPerso2) {
		this.telPerso2 = telPerso2;
	}

	public String getTelPro1() {
		return this.telPro1;
	}

	public void setTelPro1(String telPro1) {
		this.telPro1 = telPro1;
	}

	public String getTelPro2() {
		return this.telPro2;
	}

	public void setTelPro2(String telPro2) {
		this.telPro2 = telPro2;
	}

	public String getBureau() {
		return this.bureau;
	}

	public void setBureau(String bureau) {
		this.bureau = bureau;
	}

	public String getCleSalle() {
		return this.cleSalle;
	}

	public void setCleSalle(String cleSalle) {
		this.cleSalle = cleSalle;
	}

	public String getCourrielPro() {
		return this.courrielPro;
	}

	public void setCourrielPro(String courrielPro) {
		this.courrielPro = courrielPro;
	}

	public String getCourrielPro2() {
		return this.courrielPro2;
	}

	public void setCourrielPro2(String courrielPro2) {
		this.courrielPro2 = courrielPro2;
	}

	public String getFaxPro() {
		return this.faxPro;
	}

	public void setFaxPro(String faxPro) {
		this.faxPro = faxPro;
	}

	public String getUrlPro() {
		return this.urlPro;
	}

	public void setUrlPro(String urlPro) {
		this.urlPro = urlPro;
	}

	public String getDuree() {
		return this.duree;
	}

	public void setDuree(String duree) {
		this.duree = duree;
	}

	public String getEmploiPrincipal() {
		return this.emploiPrincipal;
	}

	public void setEmploiPrincipal(String emploiPrincipal) {
		this.emploiPrincipal = emploiPrincipal;
	}

	public String getStatut() {
		return this.statut;
	}

	public void setStatut(String statut) {
		this.statut = statut;
	}

	public String getFonction() {
		return this.fonction;
	}

	public void setFonction(String fonction) {
		this.fonction = fonction;
	}

	public String getResponsabilites() {
		return this.responsabilites;
	}

	public void setResponsabilites(String responsabilites) {
		this.responsabilites = responsabilites;
	}

	public String getReferent() {
		return this.referent;
	}

	public void setReferent(String referent) {
		this.referent = referent;
	}

	public String getEmployeur() {
		return this.employeur;
	}

	public void setEmployeur(String employeur) {
		this.employeur = employeur;
	}

	public byte getLabo() {
		return this.labo;
	}

	public void setLabo(byte labo) {
		this.labo = labo;
	}

	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	public String getRemarquesAdmin() {
		return this.remarquesAdmin;
	}

	public void setRemarquesAdmin(String remarquesAdmin) {
		this.remarquesAdmin = remarquesAdmin;
	}

	public String getRemarquesPerso() {
		return this.remarquesPerso;
	}

	public void setRemarquesPerso(String remarquesPerso) {
		this.remarquesPerso = remarquesPerso;
	}

	public String getAuteurModif() {
		return this.auteurModif;
	}

	public void setAuteurModif(String auteurModif) {
		this.auteurModif = auteurModif;
	}

	public Date getDateModif() {
		return this.dateModif;
	}

	public void setDateModif(Date dateModif) {
		this.dateModif = dateModif;
	}

	public Date getDateConnexion() {
		return this.dateConnexion;
	}

	public void setDateConnexion(Date dateConnexion) {
		this.dateConnexion = dateConnexion;
	}

	public byte getDel() {
		return this.del;
	}

	public void setDel(byte del) {
		this.del = del;
	}

	public String getEnsCompetences() {
		return this.ensCompetences;
	}

	public void setEnsCompetences(String ensCompetences) {
		this.ensCompetences = ensCompetences;
	}

	public byte getActiviteEns() {
		return this.activiteEns;
	}

	public void setActiviteEns(byte activiteEns) {
		this.activiteEns = activiteEns;
	}

	public byte getActiviteRech() {
		return this.activiteRech;
	}

	public void setActiviteRech(byte activiteRech) {
		this.activiteRech = activiteRech;
	}

	public byte getActiviteAdmin() {
		return this.activiteAdmin;
	}

	public void setActiviteAdmin(byte activiteAdmin) {
		this.activiteAdmin = activiteAdmin;
	}

	public byte getActiviteTechn() {
		return this.activiteTechn;
	}

	public void setActiviteTechn(byte activiteTechn) {
		this.activiteTechn = activiteTechn;
	}

	public byte getActiviteAutre() {
		return this.activiteAutre;
	}

	public void setActiviteAutre(byte activiteAutre) {
		this.activiteAutre = activiteAutre;
	}

}
